/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.humaniq.faceenginemobile.bindings;

final class ImageFormat {
    public final static ImageFormat FMT_R8G8B8A8 = new ImageFormat("FMT_R8G8B8A8");
    public final static ImageFormat FMT_Y8 = new ImageFormat("FMT_Y8");
    public final static ImageFormat FMT_YUV420sp = new ImageFormat("FMT_YUV420sp");
    private static ImageFormat[] swigValues = {FMT_R8G8B8A8, FMT_Y8, FMT_YUV420sp};
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;

    private ImageFormat(String swigName) {
        this.swigName = swigName;
        this.swigValue = swigNext++;
    }

    private ImageFormat(String swigName, int swigValue) {
        this.swigName = swigName;
        this.swigValue = swigValue;
        swigNext = swigValue + 1;
    }

    private ImageFormat(String swigName, ImageFormat swigEnum) {
        this.swigName = swigName;
        this.swigValue = swigEnum.swigValue;
        swigNext = this.swigValue + 1;
    }

    public static ImageFormat swigToEnum(int swigValue) {
        if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
            return swigValues[swigValue];
        for (ImageFormat swigValue1 : swigValues)
            if (swigValue1.swigValue == swigValue)
                return swigValue1;
        throw new IllegalArgumentException("No enum " + ImageFormat.class + " with value " + swigValue);
    }

    public final int swigValue() {
        return swigValue;
    }

    public String toString() {
        return swigName;
    }
}

