/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.humaniq.faceenginemobile.bindings;

final class Point {
    private transient boolean swigCMemOwn;
    private transient long swigCPtr;

    Point(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public Point() {
        this(WrapperJNI.new_Point__SWIG_0(), true);
    }

    public Point(int x, int y) {
        this(WrapperJNI.new_Point__SWIG_1(x, y), true);
    }

    static long getCPtr(Point obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() throws Throwable {
        delete();
        super.finalize();
    }

    private synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                WrapperJNI.delete_Point(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public int getX() {
        return WrapperJNI.Point_x_get(swigCPtr, this);
    }

    public void setX(int value) {
        WrapperJNI.Point_x_set(swigCPtr, this, value);
    }

    public int getY() {
        return WrapperJNI.Point_y_get(swigCPtr, this);
    }

    public void setY(int value) {
        WrapperJNI.Point_y_set(swigCPtr, this, value);
    }

}
